### ISSUE TITLE
点击事件前的动来动去

### ISSUE THREAD

**Issue by vxst** [LittleAprilFool/mirror#1]
话说在点击事件发生前球是不是应该一直在动呢～或者应该让鼠标移到某个随机的地点才能停？

**Comment by LittleAprilFool** [comment]
诶？球不是会跟着鼠标动吗～（（虽然其实是相机在动、点击了之后发生的事情我还没写完。。总之是个大脑洞。。

**Comment by vxst** [comment]
把mouse.x/y设置成相机最终位置会导致球在动一小会儿以后突然停下来，感觉很心塞。不如把mouse.x/y设置成相机旋转的速度什么的，这样只要鼠标不放在平衡位置球就一直会动；我们把平衡位置的xy随机，这样每一次启动就能找一下平衡位置什么的，感觉蛮有乐趣的。
